apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat-agent
  labels:
    app: filebeat-agent
spec:
  selector:
    matchLabels:
      name: filebeat-agent
  template:
    metadata:
      labels:
        name: filebeat-agent
    spec:
      containers:
      - name: filebeat
        image: tf-1:5000/filebeat:5.6.12
        resources:
          limits:
            memory: 1000Mi
          requests:
            cpu: 200m
            memory: 400Mi
        volumeMounts:
        - name: fb-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: container-logs
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: pod-logs
          mountPath: /var/log/pods
        - name: test-logs
          mountPath: /tmp/testlog
      volumes:
      - name: fb-config 
        configMap:
          name: fb-cm
          items:
          - key: filebeat.yml
            path: filebeat.yml
      - name: container-logs
        hostPath:
          path: /var/lib/docker/containers
      - name: pod-logs
        hostPath:
          path: /var/log/pods
      - name: test-logs
        hostPath:
          path: /tmp/testlog
      securityContext:
        fsGroup: 0
        runAsUser: 0
