apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: deep-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deep-kube
  template:
    metadata:
      labels:
        app: deep-kube
    spec:
      containers:
      - name: deep-kube
        image: tf-1:5000/code:10.0
        ports:
        - containerPort: 12345
        volumeMounts:
          - name: glusterfsvol
            mountPath: /mnt
      volumes:
        - name: glusterfsvol
          glusterfs:
            endpoints: glusterfs-cluster
            path: gv1/good
