filebeat.prospectors:
- input_type: log
  paths:
    - /var/log/pods/*/*/0.log
  symlinks: true
  json.keys_under_root: true
  json.overwrite_keys: true

processors:
- add_cloud_metadata:

output.logstash:
  hosts: ['logstash-server:5044']
