apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: zk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
      - name: zk
        image: zookeeper:3.5.4-beta
        ports:
        - containerPort: 2181 
