kind: Job
apiVersion: batch/v1
metadata:
    name: t2-tf-dis-ps-1-0
spec:  
  template:
    metadata:
      name: t2-tf-dis-ps-1-0
      labels:
        tf: t2-tf-dis-ps-1-0
    spec:
      containers:
      - name: t2-tf-dis-ps-1-0
        image: tf-1:5000/tf-hdfs-gfs:1.0
        ports:
        - containerPort: 2222
        command: ["bash", "-c"]
        args: ["echo 'foobar' && ls -l && sleep 20 && echo 'haha'"]
        securityContext:
            privileged: true
        volumeMounts:
        - mountPath: /mnt
          name: glusterfsvol
      volumes:
      - name: glusterfsvol
        glusterfs:
          endpoints: glusterfs-cluster
          path: gv1
      restartPolicy: Never
  backoffLimit: 0

