kind: Job
apiVersion: batch/v1
metadata:
  name: t2-tf-dis-worker-2-1
spec:
  template:
    metadata:
      name: t2-tf-dis-worker-2-1
      labels:
        tf: t2-tf-dis-worker-2-1
    spec:
      containers:
      - name: t2-tf-dis-worker-2-1
        image: tf-1:5000/test-tf14:1.0
        resources:     
            limits:
              cpu: "800m"
              memory: "4Gi"
        ports:
        - containerPort: 2222
        command: ["sleep", "3600"]
      restartPolicy: Never
