apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: es-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-server
  template:
    metadata:
      labels:
        app: es-server
    spec:
      containers:
      - name: elasticsearch
        image: tf-1:5000/elasticsearch:5.6.12
        resources:
          requests:
            cpu: 200m
            memory: 1000Mi
        ports:
        - containerPort: 9200
        volumeMounts:
          - name: es-config
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
      volumes:
        - name: es-config
          configMap:
            name: es-cm
            items:
            - key: elasticsearch.yml
              path: elasticsearch.yml
