kind: Job
apiVersion: batch/v1
metadata:
  name: tf-dis-worker-2-1
spec:
  template:
    metadata:
      name: tf-dis-worker-2-1
      labels:
        tf: tf-dis-worker-2-1
    spec:
      containers:
      - name: tf-dis-worker-2-1
        image: tf-1:5000/tf-dis:1.0
        ports:
        - containerPort: 2222
        command: ["sleep", "3600"]
      restartPolicy: Never
