apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kibana-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-server
  template:
    metadata:
      labels:
        app: kibana-server
    spec:
      containers:
      - name: kibana
        image: tf-1:5000/kibana:5.6.12
        resources:
          requests:
            cpu: 200m
            memory: 1000Mi
        ports:
        - containerPort: 5601
        volumeMounts:
          - name: kb-config
            mountPath: /usr/share/kibana/config/kibana.yml
            subPath: kibana.yml
      volumes:
        - name: kb-config
          configMap:
            name: kb-cm
            items:
            - key: kibana.yml
              path: kibana.yml
