apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: jupyter
        image: tf-1:5000/jupyter:1.0
        command: ["jupyter", "notebook", "--allow-root"]
        ports:
        - containerPort: 8888
