apiVersion: v1
kind: Service
metadata:
  name: tf-serving-cluster
spec:
  ports:
  - name: rpc
    port: 8500
    targetPort: rpc
  - name: http
    port: 8501
    targetPort: http
  selector:
    app: tf-serving

